using System;

namespace WowStatConstants
{
	public enum GARR_ABILITY_ACTION
	{
		COUNTER_MECHANIC = 0,
		SOLO_MISSION = 1,
		MOD_SUCCESS_CHANCE = 2,
		MOD_TRAVEL_TIME = 3,
		MOD_XP = 4,
		FRIENDLY_RACE = 5,
		LONG_MISSION = 6,
		SHORT_MISSION = 7,
		MOD_CURRENCY = 8,
		LONG_TRAVEL = 9,
		SHORT_TRAVEL = 10,
		MOD_BIAS = 11,
		PROFESSION = 12,
		MOD_BRONZE_LOOT_CHANCE = 13,
		MOD_SILVER_LOOT_CHANCE = 14,
		MOD_GOLD_LOOT_CHANCE = 15,
		MOD_ALL_LOOT_CHANCE = 16,
		MOD_MISSION_TIME = 17,
		MENTORING = 18,
		MOD_GOLD = 19,
		PREVENT_DEATH = 20,
		TREASURE_ON_MISSION_SUCCESS = 21,
		FRIENDLY_CLASS = 22,
		ADVANTAGE_MECHANIC = 23,
		MOD_SUCCESS_PER_DURABILITY = 24,
		MOD_SUCCESS_DURABILITY_IN_RANGE = 25,
		FRIENDLY_FOLLOWER = 26,
		KILL_TROOPS = 27,
		MOD_DURABILITY_COST = 28,
		MOD_BONUS_LOOT_CHANCE = 29,
		MOD_XP_FLAT = 30,
		MOD_ITEMLEVEL = 31,
		MOD_STARTING_DURABILITY = 32,
		UNIQUE_TROOPS = 33,
		MOD_CLASSSPEC_LIMIT = 34,
		TROOP_RESURRECTION = 35,
		MOD_COST_BY_RACE = 36,
		REWARD_ON_WORLD_QUEST_COMPLETE = 37,
		MOD_SUCCESS_BY_MISSIONS_IN_PROGRESS = 38,
		MOD_MISSION_COST = 39
	}
}
