using System;

namespace JamLib
{
	public enum JAM_DESTINATION
	{
		JAM_DESTINATION_WORLD = 0,
		JAM_DESTINATION_USER = 1,
		JAM_DESTINATION_SPAWN_ZONE = 2,
		JAM_DESTINATION_MAELSTROM = 3,
		JAM_DESTINATION_SCRYE = 4,
		JAM_DESTINATION_GLOBAL = 5,
		JAM_DESTINATION_PROXY = 6,
		JAM_DESTINATION_WEB = 7,
		JAM_DESTINATION_CHAT = 8,
		JAM_DESTINATION_PARTY = 9,
		JAM_DESTINATION_ROUTER = 10,
		JAM_DESTINATION_LFG = 11,
		JAM_DESTINATION_USER_ROUTER = 12,
		JAM_DESTINATION_GMSUPPORT = 13,
		JAM_DESTINATION_JSON_CLIENT = 14,
		JAM_DESTINATION_WOWCONTROLLER = 15,
		JAM_DESTINATION_ACCOUNT = 16,
		JAM_DESTINATION_PET_BATTLE = 17,
		JAM_DESTINATION_MOBILE = 18,
		JAM_DESTINATION_LOG = 19,
		JAM_DESTINATION_ASSET_MANIFEST = 20,
		JAM_DESTINATION_ASSET_QUERY = 21,
		JAM_DESTINATION_CHARACTER = 22,
		JAM_DESTINATION_SERVER_APP = 23,
		JAM_DESTINATION_COMMERCE = 24,
		JAM_DESTINATION_UTILITY = 25,
		JAM_DESTINATION_SHARD_MANAGER = 26,
		JAM_DESTINATION_PUBLISHER = 27
	}
}
