using System;

namespace bgs
{
	public enum BnetFeatureEvent
	{
		Auth_Logon = 0,
		Auth_OnFinish = 1,
		Auth_GameAccountSelected = 2,
		Friends_Created = 3,
		Friends_OnCreated = 4,
		Friends_OnAcceptInvitation = 5,
		Friends_OnRevokeInvitation = 6,
		Friends_OnDeclineInvitation = 7,
		Friends_OnIgnoreInvitation = 8,
		Friends_OnSendInvitation = 9,
		Friends_OnRemoveFriend = 10,
		Games_Created = 11,
		Games_OnCreated = 12,
		Games_OnQueueLeft = 13,
		Games_OnMatchmakerEnd = 14,
		Games_OnEnteredGame = 15,
		Games_OnFindGame = 16,
		Games_OnCancelGame = 17,
		Games_OnClientRequest = 18,
		Games_OnGetAllValuesForAttribute = 19,
		LocalStore_Created = 20,
		LocalStore_OnCreated = 21,
		Party_API_Created = 22,
		Party_API_OnCreated = 23,
		Party_Create_Callback = 24,
		Party_Join_Callback = 25,
		Party_Leave_Callback = 26,
		Party_Dissolve_Callback = 27,
		Party_SetPrivacy_Callback = 28,
		Party_SendInvite_Callback = 29,
		Party_AcceptInvite_Callback = 30,
		Party_DeclineInvite_Callback = 31,
		Party_RevokeInvite_Callback = 32,
		Party_RequestPartyInvite_Callback = 33,
		Party_IgnoreInviteRequest_Callback = 34,
		Party_KickMember_Callback = 35,
		Party_SendChatMessage_Callback = 36,
		Party_ClearAttribute_Callback = 37,
		Party_SetAttribute_Callback = 38,
		Party_AssignRole_Callback = 39,
		Presence_Created = 40,
		Presence_OnCreated = 41,
		Presence_OnRegisterConsumer = 42,
		Presence_OnPublishRichPresence = 43,
		Presence_OnRequestPresenceFields = 44,
		Whisper_Created = 45,
		Whisper_OnCreated = 46,
		Whisper_OnSend = 47,
		Bnet_OnConnected = 48,
		Bnet_OnDisconnected = 49,
		Challenge_Created = 50,
		Challenge_OnCreated = 51,
		Interface_GetLaunchOption = 52,
		Resources_Created = 53,
		ProfanityFilter_Created = 54,
		Broadcast_Created = 55,
		Broadcast_OnCreated = 56,
		Notification_Created = 57,
		Notification_OnCreated = 58
	}
}
