using System;

namespace bgs
{
	public enum LeaveReason
	{
		MEMBER_LEFT = 0,
		MEMBER_KICKED = 1,
		DISSOLVED_BY_MEMBER = 2,
		MEMBER_DISCONNECTED = 3,
		MEMBER_REMOVED_BY_SERVICE = 4,
		DISSOLVED_BY_SERVICE = 5,
		DISCONNECTED = 6,
		UNKNOWN = 7,
		PLAYER_REMOVED_BY_GAME_SERVER = 8,
		GAME_ENDED_BY_GAME_SERVER = 9,
		PLAYER_DISCONNECTED_FROM_GAME_SERVER = 10,
		GAME_SERVER_DISCONNECTED_FROM_SERVICE = 11,
		CHANNEL_HOST_DISCONNECTED_FROM_SERVICE = 12,
		GAME_MASTER_DISCONNECTED_FROM_SERVICE = 13,
		FOUNDER_LEFT = 14
	}
}
